{"name": "Проверка, что система возвращает ошибку при неверном логине. POST /api/v1/courier/login", "status": "passed", "start": 1759660373950, "stop": 1759660374405, "uuid": "b9fea6cc-a445-437a-910f-675c1161cd9c", "historyId": "1b65b89d5cce15034cd6a5d7820b5266", "testCaseId": "1b65b89d5cce15034cd6a5d7820b5266", "fullName": "tests.test_login_courier.TestsCourierLogin#test_login_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestsCourierLogin"}, {"name": "host", "value": "Natalias-MacBook-Air.local"}, {"name": "thread", "value": "35525-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestsCourierLogin"]}